Repository CS2113-AY1819S1-W13-1/main, pull requests merged in 2018-11, with the labels that each got.

#102 Updated README.adoc Picture
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/team/bennchong.adoc
Labels: priority.high, severity.High, status.complete, type.docs, type.epic

#106 Updating Documentation for tomorrow
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AfterAddingFriendsPS.png
  docs/images/BeforeAddingFriendsPS.png
  docs/images/FriendClassDiagram.png
  docs/images/FriendFeatureFrontEndDiagram.PNG
  docs/team/cjinting-nus.adoc
Labels: priority.high, status.complete, type.docs

#105 User Guide for Tomorrow
  docs/UserGuide.adoc
  docs/images/Login page.png
  docs/images/LoginPage.png
  docs/team/bennchong.adoc
Labels: severity.High, status.complete, type.docs

#109 Fix select command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
Labels: priority.medium, status.complete, type.bug

#146 Fixed "Me" appearing in Other's panel
  src/main/java/seedu/address/model/person/FriendListPredicate.java
  src/main/java/seedu/address/model/person/OtherListPredicate.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.medium, status.complete, type.bug

#147 Fixed "List" Command. Updated aliases. Updated UG to reflect changes.
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FriendCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnfriendCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: priority.medium, status.complete, type.bug

#149 Fixed UI to show tags in others
  src/main/java/seedu/address/ui/OtherPersonCard.java
Labels: priority.low, status.complete, type.bug

#151 Quick fix for "Find" Command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.high, severity.medium, status.complete, type.bug

#152 Updating Documentation for final product
  docs/UserGuide.adoc
  docs/images/AfterAddingFriendsPS.png
  docs/images/AfterRemovingFriendsPS.png
  docs/images/BeforeAddingFriendsPS.png
  docs/images/BeforeRemovingFriendsPS.png
  docs/images/FreeTimeMainScreen.PNG
  docs/images/StartUpScreen.PNG
  docs/images/TagCommandDefault.PNG
  docs/images/TagCommandExecutedPS.png
Labels: status.complete, type.docs

#154 Import export feature bugfix & more_tests
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/IcsUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/FileLocation.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TimeTable.java
  src/main/java/seedu/address/storage/IcsTimeTableStorage.java
  src/main/java/seedu/address/storage/TimeTableStorage.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TimeTablePanel.java
  src/main/java/seedu/address/ui/TimeTablePanelDayMarkerGrid.java
  src/main/java/seedu/address/ui/TimeTablePanelTimeMarkerGrid.java
  src/test/data/IcsUtilTest/real.ics
  src/test/data/ImportCommandTest/empty.ics
  src/test/data/ImportCommandTest/no_data.ics
  src/test/data/ImportCommandTest/no_timetable_data.ics
  src/test/data/ImportCommandTest/typical.ics
  src/test/java/seedu/address/commons/util/IcsUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/ModelStubImportExportCommand.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
Labels: status.complete

#143 Timetable Enhancements
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/model/TimeTableChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddTimeCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
  src/main/java/seedu/address/logic/commands/FreeCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/FreeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/DeconflictTimeTable.java
  src/main/java/seedu/address/model/person/TimeSlot.java
  src/main/java/seedu/address/model/person/TimeTable.java
  src/main/java/seedu/address/model/person/exceptions/TimeTableEmptyException.java
  src/main/java/seedu/address/ui/TimeTablePanel.java
  src/main/java/seedu/address/ui/TimeTablePanelDayMarkerGrid.java
  src/main/java/seedu/address/ui/TimeTablePanelMainGrid.java
  src/main/java/seedu/address/ui/TimeTablePanelTimeMarkerGrid.java
  src/main/java/seedu/address/ui/TimeTablePanelTimeSlot.java
  src/main/resources/view/TimeTablePanelMainGrid.fxml
  src/main/resources/view/TimeTablePanelTimeMarkerGrid.fxml
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/TimeTableTest.java
  src/test/java/seedu/address/testutil/TypicalTimeSlots.java
Labels: priority.medium, status.complete, type.enhancement

#162 Changed min app size to 1280x720
  .gitignore
  build.gradle
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.medium, status.complete

#165 Added error message to ImportCommand- overlapping timeslot
  src/main/java/seedu/address/commons/util/IcsUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/test/data/ImportCommandTest/overlap.ics
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: status.complete

#167 Sample data updates
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.high, status.ongoing, type.task

#172 Added colours to group tags
  src/main/java/seedu/address/ui/OtherPersonCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
Labels: priority.low, status.complete, type.enhancement

#166 Free command now shows free slots in green
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/DeconflictTimeTable.java
  src/main/java/seedu/address/model/person/TimeSlot.java
  src/main/java/seedu/address/ui/TimeTablePanel.java
  src/test/java/seedu/address/model/person/TimeSlotTest.java
Labels: priority.medium, status.complete, type.enhancement

#169 Added more sample data
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/SampleTimeTableUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
Labels: priority.medium, status.complete, type.task

#173 Final UG Update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/FreeTimeMainScreenFix.png
  docs/images/FriendFeatureFrontEndDiagramFix.png
  docs/images/StartUpScreenFix.png
  docs/images/TagCommandDefaultFix.png
  src/main/java/seedu/address/logic/commands/FriendCommand.java
Labels: status.complete, type.docs

#170 Fixed Me updating after EditCommand + Bug Fixes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTimeCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FreeCommand.java
  src/main/java/seedu/address/logic/commands/FriendCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UnfriendCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/CombinedFriendPredicate.java
  src/main/java/seedu/address/model/person/CombinedOtherPredicate.java
  src/main/java/seedu/address/model/person/FriendListPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MePanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: severity.medium, status.complete, type.task

#178 Default accounts
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/security/AppUsers.java
Labels: priority.high, severity.low, status.complete

#168 Last bunch of PPP updates
  README.adoc
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DeconflictSequenceDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/ImportSequenceDiagram.png
  docs/diagrams/TimeTableClassDiagram.pptx
  docs/diagrams/TimeTablePanelClassDiagram.pptx
  docs/diagrams/UpdateTimeTableSequenceDiagram.pptx
  docs/images/DeconflictSequenceDiagram.png
  docs/images/TimeTableClassDiagram.png
  docs/images/TimeTablePanelClassDiagram.png
  docs/images/UpdateTimeTableSequenceDiagram.png
  docs/team/nianfei97.adoc
Labels: status.complete, type.docs

#181 Added Alias + Removed Logout Button
  src/main/java/seedu/address/commons/CommandsEnum.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FreeCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: status.complete, type.bug

#182 Removed UserStub + Changed alias for group command
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/security/UserStub.java
Labels: priority.high, status.complete, type.task

#177 Quickfix - timezones borking up import/export commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/DateTimeConversionUtil.java
  src/main/java/seedu/address/commons/util/IcsUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/TimeSlot.java
  src/test/java/seedu/address/commons/util/IcsUtilTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
Labels: priority.medium, status.complete, type.bug

#185 User timetable is seen right after logging in
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: status.complete, type.bug

#184 Instructions for Manual Testing in DG
  docs/DeveloperGuide.adoc
Labels: status.complete, type.docs

#186 Bug fix for allowing users with same name to register
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/commons/ModelManagerTestUserStub.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/RegisterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandTest.java
Labels: severity.high, status.complete, type.bug

#176 Update version to v1.4
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: priority.high, status.complete

#189 Changed all outward-facing mentions of tags to groups
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.high, status.complete

#190 Updated diagrams for add and remove timeslots
  docs/UserGuide.adoc
  docs/diagrams/AddTimeSuccessDiagram.pptx
  docs/diagrams/FreeTimeSuccessDiagram.pptx
  docs/images/AddTimeSuccess.png
  docs/images/FreeTimeSuccess.png
Labels: status.complete, type.docs

#191 Update command alias of some commands
  src/main/java/seedu/address/logic/commands/AddTimeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: status.complete, type.bug

#188 Ppp final
  docs/DeveloperGuide.adoc
  docs/diagrams/ExportSequenceDiagram.pptx
  docs/diagrams/ImportSequenceDiagram.pptx
  docs/images/ExportSequenceDiagram.png
  docs/images/ImportSequenceDiagram.png
  docs/images/UG_export_directory.png
  docs/images/UG_export_step_1.png
  docs/images/UG_export_step_2.png
  docs/images/UG_export_step_3.png
  docs/images/UG_import_directory.png
  docs/images/UG_import_step_1.png
  docs/images/UG_import_step_2.png
  docs/images/UG_import_step_3.png
  docs/images/UG_import_step_4.png
  docs/images/UG_importexport.png
  docs/images/importics.png
  docs/team/alexiscatnip.adoc
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
Labels: status.complete, type.docs

#195 Updating Ben's edits into main
  docs/UserGuide.adoc
  docs/images/AfterAddingFriendsPS.png
  docs/images/AfterRemovingFriendsPS.png
  docs/images/BeforeAddingFriendsPS.png
  docs/images/BeforeRemovingFriendsPS.png
  docs/images/LoginPage.png
  docs/images/LoginUI.png
  docs/images/Logout.png
  docs/images/RegisterUI.png
  docs/images/StartUpScreenFix.png
Labels: status.complete, type.docs

#194 Ppp - final retification
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/alexiscatnip_PPP_overview.png
  docs/team/alexiscatnip.adoc
Labels: status.complete, type.docs

#201 Ppp - 10 pages
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ExportSequenceDiagram.pptx
  docs/diagrams/ImportSequenceDiagram.pptx
  docs/images/ExportSequenceDiagram.png
  docs/images/ImportSequenceDiagram.png
  docs/team/alexiscatnip.adoc
Labels: status.complete, type.docs

#202 PPP Merge
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/SecurityParseCommandsSequenceDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/Architecture.png
  docs/images/LoginUI.png
  docs/images/Logout.png
  docs/images/RegisterUI.png
  docs/images/SecurityLoginSequenceDiagram.png
  docs/images/SecurityParseCommandsSD.png
  docs/images/StorageClassDiagram.png
  docs/team/bennchong.adoc
Labels: type.docs

#203 Raised Issues
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/LoginUI.png
  docs/images/RegisterUI.png
  docs/team/bennchong.adoc
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: status.complete
