Repository CS2113-AY1819S1-W13-1/main, pull requests merged in 2018-10, with the labels that each got.

#11 Fix badges on README.adoc, update ContactUs.adoc
  README.adoc
  docs/ContactUs.adoc
Labels: status.complete

#9 Feature/test branch
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SetTimeTable.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TimeSlot.java
  src/main/java/seedu/address/model/person/TimeTable.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/SetTimeTableTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: status.complete

#10 Timetable UI feature
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TimeTablePanel.java
  src/main/java/seedu/address/ui/TimeTablePanelDaySlot.java
  src/main/java/seedu/address/ui/TimeTablePanelMainGrid.java
  src/main/java/seedu/address/ui/TimeTablePanelTimeSlot.java
  src/main/java/seedu/address/ui/TimeTablePanelTimingGrid.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TimeTablePanel.fxml
  src/main/resources/view/TimeTablePanelDaySlot.fxml
  src/main/resources/view/TimeTablePanelMainGrid.fxml
  src/main/resources/view/TimeTablePanelTimeSlot.fxml
  src/main/resources/view/TimeTablePanelTimingGrid.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: status.complete

#16 Photos converted to PNG, and aboutus edited.
  docs/AboutUs.adoc
  docs/images/alexiscatnip.jpg
  docs/images/alexiscatnip.png
  docs/images/bennchong.jpg
  docs/images/bennchong.png
  docs/images/cjinting-nus.jpg
  docs/images/cjinting-nus.png
  docs/images/nianfei97.jpg
  docs/images/nianfei97.png
  docs/images/okkhoy.jpg
  docs/images/okkhoy.png
Labels: priority.high

#17 Added config file
  .gitignore
  config.json
Labels: status.complete

#18 Merge from upstream se-edu/AB4
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedTag.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: status.complete, type.bug

#19 WIP Security package
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/security/SuccessfulLoginEvent.java
  src/main/java/seedu/address/commons/events/security/UnsuccessfulLoginEvent.java
  src/main/java/seedu/address/security/Security.java
  src/main/java/seedu/address/security/SecurityManager.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/login.png
  src/main/resources/view/LoginWindow.fxml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
Labels: status.ongoing, type.epic

#34 Change app name in config.json, add config.json to .gitignore
  .gitignore
  config.json
Labels: status.complete, type.bug

#31 Edited UG/DG for Security Component
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/SecurityComponentClassDiagram.pptx
  docs/diagrams/SecurityLogInSequenceDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/Architecture.png
  docs/images/Security.PNG
  docs/images/SecurityClassDiagram.png
  docs/images/SecurityLoginSequenceDiagram.png
  src/main/java/seedu/address/security/SecurityManager.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.high, status.complete

#39 Added Unit Test for SecurityManager
  src/test/java/seedu/address/security/SecurityManagerTest.java
Labels: priority.high, status.ongoing

#35 Friend List feature
  .travis.yml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTimeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FriendCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/UnfriendCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FriendCommandParser.java
  src/main/java/seedu/address/logic/parser/UnfriendCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Friend.java
  src/main/java/seedu/address/model/person/FriendListPredicate.java
  src/main/java/seedu/address/model/person/OtherListPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/security/UserStub.java
  src/main/java/seedu/address/storage/XmlAdaptedFriend.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/FriendListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/FreeTime_32.png
  src/main/resources/images/address_book_32.png
  src/main/resources/view/FriendListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.high, status.complete, type.epic

#45 Removed config.json from tracked files
  config.json
Labels: priority.high, type.bug

#46 Testing config.json again
  config.json
Labels: type.bug

#49 Update UG
  docs/UserGuide.adoc
  docs/images/AddTimeSuccess.png
Labels: status.complete

#51 Fix some issues from peer review session of UG/DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Security.png
Labels: priority.high, status.complete, type.docs

#55 Timetable import and export feature
  build.gradle
  src/main/java/seedu/address/commons/util/IcsUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/TimeSlot.java
  src/main/java/seedu/address/model/person/TimeTable.java
  src/main/java/seedu/address/storage/IcsTimeTableStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TimeTableStorage.java
Labels: priority.high, status.complete, type.story

#40 V1.3 User Class (matchPerson works)
  docs/DeveloperGuide.adoc
  docs/team/bennchong.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/security/LogoutEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowLoginEvent.java
  src/main/java/seedu/address/commons/events/ui/SuccessfulRegisterEvent.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/User.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UserParameterHelper.java
  src/main/java/seedu/address/security/Security.java
  src/main/java/seedu/address/security/SecurityManager.java
  src/main/java/seedu/address/security/User.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RegistrationWindow.java
  src/main/java/seedu/address/ui/SecurityBox.java
  src/main/java/seedu/address/ui/SecurityResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/LoginWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MainWindowSB.fxml
  src/main/resources/view/SecurityBox.fxml
  src/main/resources/view/SecurityResultDisplay.fxml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/security/SecurityManagerTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
Labels: priority.high, status.complete, type.epic

#53 Midv1.3
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTimeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/DeconflictTimeTable.java
  src/main/java/seedu/address/model/person/TimeSlot.java
  src/main/java/seedu/address/model/person/TimeTable.java
  src/main/java/seedu/address/model/person/exceptions/TimeSlotNotOverlapException.java
  src/main/java/seedu/address/ui/TimeTablePanel.java
  src/main/java/seedu/address/ui/TimeTablePanelMainGrid.java
  src/test/java/seedu/address/logic/commands/AddTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTimeCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DeconflictTimeTableTest.java
  src/test/java/seedu/address/model/person/TimeSlotTest.java
  src/test/java/seedu/address/model/person/TimeTableTest.java
  src/test/java/seedu/address/testutil/TypicalTimeSlots.java
Labels: priority.high, status.complete

#61 User in ModelManager Self-updates when database changes
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.high, status.complete

#62 Logout UI with logout command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/security/SecurityManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/security/SecurityManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: priority.high, status.complete, type.task

#67 Removed mutiple selection property from code
  src/main/java/seedu/address/storage/XmlAdaptedFriend.java
  src/main/java/seedu/address/ui/FriendListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.medium, status.complete, type.bug

#68 Friend/Unfriend Command + MePanel Features
  src/main/java/seedu/address/logic/commands/FriendCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UnfriendCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/CombinedFriendPredicate.java
  src/main/java/seedu/address/model/person/CombinedOtherPredicate.java
  src/main/java/seedu/address/model/person/Friend.java
  src/main/java/seedu/address/model/person/FriendListPredicate.java
  src/main/java/seedu/address/model/person/OtherListPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/security/UserStub.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MePanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MePanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.high, status.complete, type.story

#63 Security V1.3 User Database
  .gitignore
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/security/AccountCredential.java
  src/main/java/seedu/address/security/AppUsers.java
  src/main/java/seedu/address/security/SecurityManager.java
  src/main/java/seedu/address/storage/AppUsersStorage.java
  src/main/java/seedu/address/storage/JsonAppUsersStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SecurityBox.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MainWindowSB.fxml
  src/main/resources/view/SecurityResultDisplay.fxml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/security/AccountCredentialTest.java
  src/test/java/seedu/address/security/AppUsersTest.java
  src/test/java/seedu/address/security/AppUsersTestStub.java
  src/test/java/seedu/address/security/SecurityManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
Labels: priority.high, status.complete, type.epic

#64 Free command
  src/main/java/seedu/address/logic/commands/AddTimeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
  src/main/java/seedu/address/logic/commands/FreeCommand.java
  src/main/java/seedu/address/logic/parser/AddTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/FreeCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/DeconflictTimeTable.java
  src/main/java/seedu/address/model/person/TimeSlot.java
  src/main/java/seedu/address/model/person/TimeTable.java
  src/main/java/seedu/address/ui/TimeTablePanelMainGrid.java
  src/main/java/seedu/address/ui/TimeTablePanelTimeSlot.java
  src/main/resources/view/TimeTablePanelMainGrid.fxml
  src/main/resources/view/TimeTablePanelTimeSlot.fxml
  src/test/java/seedu/address/logic/commands/AddTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/FreeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTimeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTimeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FreeCommandParserTest.java
  src/test/java/seedu/address/model/person/DeconflictTimeTableTest.java
Labels: priority.high, status.complete, type.story

#75 Bug Fix
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/SecurityComponentClassDiagram.pptx
  docs/diagrams/SecurityLogInSequenceDiagram.pptx
  docs/images/Architecture.png
  docs/images/SecurityClassDiagram.png
  docs/images/SecurityLoginSequenceDiagram.png
  src/main/java/seedu/address/security/AccountCredential.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: severity.High, status.complete, type.bug

#80 Add sample timetables
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/SampleTimeTableUtil.java
  src/main/java/seedu/address/ui/TimeTablePanelMainGrid.java
Labels: priority.high, status.complete

#83 Delete system tests
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, severity.High, status.complete

#82 Fix select command
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/ui/FriendListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OtherListPanel.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.high, status.complete

#84 Added UG for Security Features
  docs/UserGuide.adoc
  docs/images/Login page.PNG
  docs/images/LoginUI.PNG
  docs/images/Logout.PNG
  docs/images/RegisterUI.PNG
Labels: status.complete, type.docs

#87 Update User guide and Developer guide - import and export commands
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ImportSequenceDiagram.png
  docs/diagrams/ImportSequenceDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/ImportSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: priority.high, status.complete, type.docs

#89 UG for v1.3
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddTimeSuccessDiagram.pptx
  docs/diagrams/FreeTimeSuccessDiagram.pptx
  docs/images/AddTimeSuccess.png
  docs/images/FreeTimeSuccess.png
  docs/images/Login page.png
  docs/images/LoginUI.png
  docs/images/Logout.png
  docs/images/RegisterUI.png
  docs/team/nianfei97.adoc
  src/main/java/seedu/address/logic/commands/AddTimeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTimeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.high, status.complete, type.docs

#90 Testers can login with "test" account now
  README.adoc
  docs/images/Ui.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.high, status.complete, type.bug

#77 Added TagCommand tests
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Labels: priority.medium, status.complete, type.task
